name: youtube
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - black
    - ipykernel
    - opencv-python
    - imageio==2.9.0
    - ffmpeg
    - imageio-ffmpeg==0.4.2
    - mediapipe==0.10.0
    - pandas
    - lmdb
    - h5py
    - tqdm
    - joblib
    - -e git+https://github.com/yt-dlp/yt-dlp@master#egg=yt-dlp